### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by ScottPriestley** [anfederico/flaskex#34]
Anthony, I'm sorry, Im a newb and Im sure its something Im doing wrong. 
After I run the git command and install I get all of these errors when I run python app.py
Can you give me a hint what Im doing wrong? 

Traceback (most recent call last):
  File "C:\Users\spriestley\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\spriestley\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\flask\cli.py", line 988, in main
    cli.main()
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\flask\cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\flask\cli.py", line 850, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\flask\cli.py", line 299, in __init__
    self._load_unlocked()
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\flask\cli.py", line 333, in _load_unlocked
    self._app = rv = self.loader()
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\flask\cli.py", line 393, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\venv\lib\site-packages\flask\cli.py", line 234, in locate_app
    __import__(module_name)
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\app.py", line 4, in <module>
    from scripts import forms
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\scripts\forms.py", line 6, in <module>
    class LoginForm(Form):
  File "C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx\scripts\forms.py", line 7, in LoginForm
    username = StringField('Username:', validators=[validators.required(), validators.Length(min=1, max=30)])
AttributeError: module 'wtforms.validators' has no attribute 'required'
(venv) PS C:\Users\spriestley\Dropbox\DevProjects\flask\FlaskEx>

**Comment by anfederico** [comment]
Thanks - would you mind submitting a pull request?

**Comment by michaeljameslyon** [comment]
I was not able to get the code to work with the above solution, but after checking wtforms documentation, this worked:

REPLACE THE FOLLOWING:
`
class LoginForm(Form):
    username = StringField('Username:', validators=[validators.required(), validators.Length(min=1, max=30)])
    password = StringField('Password:', validators=[validators.required(), validators.Length(min=1, max=30)])
    email = StringField('Email:', validators=[validators.optional(), validators.Length(min=0, max=50)])
`
WITH:
`
class LoginForm(Form):
    username = StringField('Username:', validators=[validators.InputRequired(), validators.Length(min=5, max=30)])
    password = StringField('Password:', validators=[validators.InputRequired(), validators.Length(min=5, max=30)])
    email = StringField('Email:', validators=[validators.Length(min=0, max=30)])
`
