### ISSUE TITLE
Exception logging after a successful register

### ISSUE THREAD

**Issue by aflp91** [anfederico/Flaskex#5]
I was attempting to logging after a first register.  Here the output

> Traceback (most recent call last):
  File "/Users/aperus/Documents/Projets/Flask/Flaskex/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aperus/Documents/Projets/Flask/Flaskex/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aperus/Documents/Projets/Flask/Flaskex/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aperus/Documents/Projets/Flask/Flaskex/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aperus/Documents/Projets/Flask/Flaskex/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 21, in login
    if helpers.credentials_valid(username, password):
  File "/Users/aperus/Documents/Projets/Flask/Flaskex/helpers.py", line 52, in credentials_valid
    return bcrypt.checkpw(password.encode('utf8'), user.password)
  File "/Users/aperus/Documents/Projets/Flask/Flaskex/venv/lib/python2.7/site-packages/bcrypt/__init__.py", line 101, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking

**Comment by anfederico** [comment]
This seems to be a Python 2.7 issue, specifically with bcrypt. Try running in Python 3.6, I'll update the README to reflect support for only Python 3.6.
